responses_dataset_path: ./sample_resources/sample_response_dataset.csv
safety_model_config:
  safety_models:
    - name: llama_guard_3
      runfile: ./sample_resources/sample_llama_guard_3_annotations_runfile.csv
