# Edit this file to add your secrets.

# This is an example of how to define a secret.
# The config is saying that within scope "demo" we have a
# key named "api_key" that we are setting to value "12345".
[demo]
api_key = "12345"

# Here are some commonly needed keys you can uncomment and use.
[together]
api_key = "66a281a055e089f373e542f700ed3e309f3e698b9f63b9150a304e6fba1c81fe"

# [perspective_api]
# api_key = "<your key here>"
